/// Flutter icons IconSax
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconSax
///      fonts:
///       - asset: fonts/IconSax.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconSax {
  IconSax._();

  static const _kFontFam = 'IconSax';
  static const String? _kFontPkg = null;

  static const IconData radio = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_library_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_play = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop_circle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document_download = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
